# Generated by Django 4.0 on 2022-01-20 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogg', '0003_addpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addPost',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='blogpost', to=settings.AUTH_USER_MODEL),
        ),
    ]
